# Generated by Django 4.2.4 on 2023-08-30 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
